site_name: "PointCloudCrafter"
site_author: TUMFTM
repo_url: https://github.com/TUMFTM/PointCloudCrafter
site_url: https://TUMFTM.github.io/PointCloudCrafter
site_description: "PointCloudCrafter: A tool for crafting and modifying point clouds."

theme:
    name: material
    palette:
        primary: indigo
    logo: assets/icon.svg
    favicon: assets/icon.svg
    font:
        text: Roboto

use_directory_urls: false

markdown_extensions:
    - meta
    - attr_list
    - admonition
    - pymdownx.highlight:
        anchor_linenums: true
    - pymdownx.inlinehilite
    - pymdownx.snippets
    - pymdownx.superfences
    - pymdownx.emoji:
        emoji_index: !!python/name:material.extensions.emoji.twemoji
        emoji_generator: !!python/name:material.extensions.emoji.to_svg

copyright: Copyright &copy; 2025 - 2026 TUMFTM

extra_css:
    - "https://maxcdn.bootstrapcdn.com/font-awesome/4.6.1/css/font-awesome.min.css"

nav:
    - Home: 'index.md'
    - docker.md
    - getting_started.md
    - usage.md
    - third-party.md
    - API: docs_cpp/index.html

exclude_docs: |
    paper.md